import fs from "fs-extra";
import path from "node:path";
import chalk from "chalk";

/**
 * Read a design-config JSON file and emit React component stubs.
 * @param {string} cfgPath – absolute or relative path to design-config.json
 * @param {string} outDir  – output directory for generated components
 */
export async function runDesignAgent(cfgPath, outDir) {
  const cfg = await fs.readJson(cfgPath);
  await fs.ensureDir(outDir);

  const { screens = [], brandColors = {}, typography = {} } = cfg;

  await Promise.all(
    screens.map(async (screen) => {
      const fname = path.join(outDir, `${screen.name}.jsx`);
      const component = `/**\n * Auto-generated by design-agent-core\n * Brand colors: ${JSON.stringify(brandColors)}\n * Typography:   ${JSON.stringify(typography)}\n */\nexport default function ${screen.name}() {\n  return <div>${screen.name} – implement me!</div>;\n}\n`;
      await fs.writeFile(fname, component);
    })
  );

  console.log(chalk.green(`✅ Generated ${screens.length} components in ${outDir}`));
}
